### ISSUE TITLE
Check the existence of pre-compressed file.

### ISSUE THREAD

**Issue by AilisObrian** [domadams/pre-compressed-assets#1]
Currently, codebase will send .br even though we don't have .br.

Why don't we just adding to check the pre-compressed file existed?

**Comment by AilisObrian** [comment]
but we don't know yet in this library.
because we just redirect .br, right?

**Comment by domadams** [comment]
Agreed - it does not yet check for existence of file which is something I will add to the library. Currently it assumes that `.br` is available and does not fall back to gzip. I will make an update to address this.

**Comment by domadams** [comment]
Fixed in version 2.0.0
